Repository Zegocover/Label-by-pr-title, pull requests merged in 2021-06, with the labels that each got.

#4 Test pr request
  .github/Label_config.yml
  .github/workflows/add-label.yml
  .gitignore
  action.yml
  dist/index.js
  index.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/action.js
Labels: good first issue, help wanted, invalid

#5 word to name to label PR as bug
  .github/Label_config.yml
  .gitignore
  action.yml
  dist/index.js
  src/action.js
Labels: bug, documentation, duplicate, enhancement, help wanted

#7 Updated README enhance
  README.md
Labels: enhancement

#8 fix :Matching changed to beginning word
  dist/index.js
  src/action.js
Labels: bug, enhancement

#6 Test using key value enhance
  dist/index.js
  src/action.js
Labels: bug, enhancement, invalid

#9 create file to contain label matching to read from
  .github/pr_label_config.yml
  .gitignore
  dist/index.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/action.js
  src/test.js
Labels: bug

#10 feat read config from file or default location
  README.md
  action.yml
  dist/index.js
  index.js
  src/action.js
Labels: feat

#11 feat output labels
  .github/pr_label_config.yml
  .github/workflows/add-label.yml
  action.yml
  dist/index.js
  src/action.js
  src/test.js
Labels: bug, feat

#13 Export labels from file
  dist/index.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/action.js
  src/labels.js
Labels: feat

#14 feat removed DefineLabels2 function
  dist/index.js
  src/action.js
Labels: feat

#15 feat Hope this ts change works
  action.yml
  dist/index.js
  index.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/action.js
  src/action.ts
  src/labels.js
  src/labels.ts
  tsconfig.json
Labels: feat

#16 feat correct label validation
  .github/workflows/add-label.yml
  README.md
  action.yml
  dist/index.js
  package.json
  src/action.js
  src/action.ts
  src/labels.js
  src/labels.ts
  src/test.js
  src/test.ts
Labels: bug, feat

#17 feat Replaced variable identifiers
  src/action.ts
Labels: bug
